### ISSUE TITLE
Feature Request: Support Eat.

### ISSUE THREAD

**Issue by jgarte** [accelbread/meow-vterm#1]
WDYT

https://codeberg.org/akib/emacs-eat

**Comment by accelbread** [comment]
Hi, I actually use eat with eshell. 

I'd make a separate meow-eat package rather than add it to this package.

I haven't bothered separating it out into a package yet since my integration with it has an issue where it will enter semi-char mode by default when running a visual command instead of entering char mode. Though going to normal mode and back to insert puts eat in char mode.

Here is my current integration: https://github.com/accelbread/config-flake/blob/640a0711386220fd632f6573758a1c5cac6457f2/dotfiles/emacs/init.el#L962
